spring:
  datasource:
    url: jdbc:h2:mem:dicedb
    driver-class-name: org.h2.Driver
    username: avalog
    password: avalog
    jpa:
      hibernate:
        ddl-auto: validate
        use-new-id-generator-mappings: true
      show-sql: true
      database-platform: org.hibernate.dialect.H2Dialect